# Generated by Django 5.2.14 on 2026-05-11 15:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingConversation',
            fields=[
                ('conv_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('info', models.JSONField(blank=True, default=dict)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '图纸会话',
                'verbose_name_plural': '图纸会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entry', to='drawings.drawingconversation')),
            ],
            options={
                'verbose_name': '知识库条目',
                'verbose_name_plural': '知识库条目',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ParseJob',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.CharField(blank=True, default='等待处理...', max_length=255)),
                ('progress_pct', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=10)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='drawings.drawingconversation')),
            ],
            options={
                'verbose_name': '解析任务',
                'verbose_name_plural': '解析任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_index', models.PositiveIntegerField(default=1)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('stored_url', models.CharField(max_length=1024)),
                ('storage_backend', models.CharField(choices=[('local', 'Local'), ('oss', 'OSS')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drawings.drawingconversation')),
            ],
            options={
                'verbose_name': '图纸文件',
                'verbose_name_plural': '图纸文件',
                'ordering': ['conversation_id', 'page_index'],
                'unique_together': {('conversation', 'page_index')},
            },
        ),
    ]
